name: here_bro
description: "Locate your bro with a NOTIFICATION"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:

  cloud_firestore: ^6.1.1
  firebase_auth: ^6.1.2
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_storage: ^13.0.5
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geolocator: ^14.0.2
  flutter_local_notifications: ^19.5.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  image_picker: ^1.2.1
  latlong2: ^0.9.1
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter:

  uses-material-design: true
  assets:
    - assets/images/HereBro.png
